# Generated by Django 5.1.7 on 2025-04-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(choices=[('CSE', 'CSE'), ('TEXTILE', 'TEXTILE'), ('BBA', 'BBA'), ('ECE', 'ECE'), ('IT', 'IT'), ('MECHANICAL', 'MECHANICAL'), ('AI', 'AI'), ('BANGLA', 'BANGLA'), ('ENGLISH', 'ENGLISH'), ('MATH', 'MATH')], max_length=30)),
                ('Phone_NO', models.PositiveIntegerField()),
            ],
        ),
    ]
